baseurl = "/"
config = "config.toml"
DefaultContentLanguage ="fr"
SectionPagesMenu = ["main", "citoyen"]
canonifyurls = true

[taxonomies]
  tag = "tags"
  categorie = "categories"
  series = "series"
  project = "projects"

[Languages]
[Languages.en]
weight = 1
title = "Manufacture of Ideas and New Experiments"
info = "Open to publicg<br> on wednesdays at 18h00<br> or contact us"
address = "1 Rue de Croix de Luizet<br> 69100 Villeurbanne"
[[Languages.en.menu.main]]
identifier = "about"
name       = "About"
url        = "/en/about"
weight     = 0

[[Languages.en.menu.main]]
identifier = "program"
name       = "Program"
url        = "/en/program/"
weight     = 1

[[Languages.en.menu.main]]
identifier = "projects"
name       = "Projects"
url        = "/en/project/"
weight     = 2

[[Languages.en.menu.main]]
  identifier = "contribute"
  name       = "Contribute"
  url        = "/en/contribute/"
  weight     = 3

[[Languages.en.menu.main]]
identifier = "agenda"
name       = "Agenda"
url        = "/en/agenda/"
weight     = 4


[Languages.fr]
weight = 2
title = "Manufacture des Idées et Nouvelles Expérimentations"
info = """Ouverture au public<br>
le Mercredi à partir de 18h<br> ou contactez-nous"""
address = "1 Rue de Croix de Luizet<br>69100 Villeurbanne"

[[Languages.fr.menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about"
  weight     = 0

[[Languages.fr.menu.main]]
  identifier = "program"
  name       = "Programme"
  url        = "/program/"
  weight     = 1

[[Languages.fr.menu.main]]
  identifier = "projects"
  name       = "Projets"
  url        = "/project/"
  weight     = 2

[[Languages.fr.menu.main]]
  identifier = "contribute"
  name       = "Contribuer"
  url        = "/contribute/"
  weight     = 3

[[Languages.fr.menu.main]]
  identifier = "agenda"
  name       = "Agenda"
  url        = "/agenda/"
  weight     = 4

[params]
  DateForm = "Monday, Jan 2"
  hometitle = "La MYNE"
  homesubtitle = "Tiers-Lieu Open Source"

  [[params.social]]
    title = "twitter"
    url = "https://twitter.com/https://twitter.com/LaPaillassaone"
    icon = "icon-twitter"
    header = "yes"
  [[params.social]]
    title = "github"
    url = "https://github.com/lamyne"
    icon = "icon-github"
    header = "yes"
  [[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/groups/644546245604963/"
    icon = "icon-facebook"
    header = "yes"
  [[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/company/la-myne-by-lps-"
    icon = "icon-linkedin"
  [[params.social]]
    title = "flickr"
    url = "https://www.flickr.com/photos/lps_myne/"
    icon = "icon-flickr"
  [[params.social]]
    title = "slack"
    url = "https://la-myne.slack.com"
    icon = "icon-slack"
    header = "yes"
  [[params.social]]
    title = "email"
    url = "team@lamyne.org"
    icon = "icon-mail"
    header = "yes"
  [[params.social]]
    title = "youtube"
    url = "https://www.youtube.com/channel/UC-AkSeIOQf3-fscKmoXfmxA"
    icon = "ion-social-youtube-outline"



[params.banner]
  [[params.banner.sections]]
  name = "Projects"
  image = "/img/project-banner.jpg"

  [[params.banner.sections]]
    name = "La MYNE"
    image = "/img/lamyne-banner.jpg"

  [[params.banner.sections]]
    name = "Contributes"
    image = "/img/contribute-banner.jpg"

  [[params.banner.sections]]
    name = "Agendas"
    image = "/img/agenda-banner.jpg"

  [[params.banner.sections]]
      name = "Programs"
      image = "/img/program-banner.jpg"


[[params.partners]]
  name = "La Paillasse"
  logo = "/img/paillasse-logo.png"
  link = "http://lapaillasse.org/"

[[params.partners]]
name = "POC Foundation"
logo = "/img/poc-foundation-logo.png"
link = "http://movilab.org/index.php?title=La_POC_Foundation"

[[params.partners]]
name = "Open Ara"
logo = "/img/open-ara-logo.png"
link = "https://openara.org/"

[[params.partners]]
name = "Cellabz"
logo = "/img/cellabz-logo.jpg"
link = "http://www.cellabz.com/"

[[params.partners]]
name = "Grand Lyon "
logo = "/img/grand-lyon-logo.png"
link = "http://www.grandlyon.com/"

[[params.partners]]
name = "INSA Lyon"
logo = "/img/insa-logo.png"
link = "https://www.insa-lyon.fr/"

[[params.partners]]
name = "La Fabrique d'Objets Libres"
logo = "/img/fol-logo.jpg"
link = "http://www.fablab-lyon.fr/"

[[params.partners]]
name = "Le Laboratoire Ouvert Lyonnais"
logo = "/img/lol-logo.png"
link = "https://labolyon.fr/"

[[params.partners]]
name = "ECAM "
logo = "/img/ecam-logo.png"
link = "http://www.ecam.fr/fr/ecam-lyon/ecam-lyon"

[[params.partners]]
name = "Ouishare"
logo = "/img/ouishare-logo.png"
link = "http://ouishare.net/fr"

[[params.partners]]
name = "ENS Lyon"
logo = "/img/ens-logo.jpg"
link = "http://www.ens-lyon.fr/"

[[params.partners]]
name = "TUBA"
logo = "/img/tuba-logo.jpg"
link = "http://www.tuba-lyon.com/"
